/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

//import Clientes.ListaCliente;
//import Paquetes.ListaPaquete;
//import Paquetes.Paquete;
import DataBase.DataBaseConnection;
import Model.Clase.Clase;
import Model.Clase.ClaseDAO;
import Model.Clase.ClaseMapper;
import Model.Entrenador.EntrenadorDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Saliim
 */
public class GUIClases extends javax.swing.JInternalFrame {

    /**
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     private ClaseDAO dao;
    private  ClaseMapper mapper;
    private EntrenadorDAO daoentrenador;
    
    
    public GUIClases(){
       initComponents();
        DisableorActiveAll(false);
        try {
            dao = new ClaseDAO(DataBaseConnection.getConnection());
            daoentrenador = new EntrenadorDAO(DataBaseConnection.getConnection());
        } catch (SQLException ex) {
            showError("Error al conectar con la Base de Datos");
        }
        mapper = new ClaseMapper();
        jComboBox1.removeAllItems();  
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        AddLbl = new javax.swing.JLabel();
        Deletelbl = new javax.swing.JLabel();
        ActualizarLbl = new javax.swing.JLabel();
        BuscarLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CancelLbl = new javax.swing.JLabel();
        listoLbl = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        HorarioRLbl = new javax.swing.JLabel();
        TipoClaseLbl = new javax.swing.JLabel();
        EntrenadorLbl = new javax.swing.JLabel();
        Capacidadlbl = new javax.swing.JLabel();
        TipoClaseTxt = new javax.swing.JTextField();
        CapacidadTxt = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        EntrenadorTxt = new javax.swing.JFormattedTextField();
        IdTxt = new javax.swing.JFormattedTextField();
        IdLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(840, 421));

        jPanel6.setBackground(new java.awt.Color(33, 37, 41));

        AddLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AddLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-new-24.png"))); // NOI18N
        AddLbl.setText("Agregar");
        AddLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLblMouseClicked(evt);
            }
        });

        Deletelbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Deletelbl.setForeground(new java.awt.Color(255, 255, 255));
        Deletelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-24.png"))); // NOI18N
        Deletelbl.setText("Eliminar");
        Deletelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletelblMouseClicked(evt);
            }
        });

        ActualizarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ActualizarLbl.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-crear-nuevo-24.png"))); // NOI18N
        ActualizarLbl.setText("Actualizar");
        ActualizarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarLblMouseClicked(evt);
            }
        });

        BuscarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BuscarLbl.setForeground(new java.awt.Color(255, 255, 255));
        BuscarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-google-web-search-24.png"))); // NOI18N
        BuscarLbl.setText("Buscar");
        BuscarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarLblMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Opciones ");

        CancelLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancelar-24.png"))); // NOI18N
        CancelLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelLblMouseClicked(evt);
            }
        });

        listoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-casilla-de-verificación-marcada-24.png"))); // NOI18N
        listoLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listoLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Deletelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(listoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Deletelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ActualizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BuscarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setOpaque(true);

        HorarioRLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        HorarioRLbl.setForeground(new java.awt.Color(255, 255, 255));
        HorarioRLbl.setText("Horario:");

        TipoClaseLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TipoClaseLbl.setForeground(new java.awt.Color(255, 255, 255));
        TipoClaseLbl.setText("Tipo de clase:");

        EntrenadorLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EntrenadorLbl.setForeground(new java.awt.Color(255, 255, 255));
        EntrenadorLbl.setText("Entrenador Asignado(ID):");

        Capacidadlbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Capacidadlbl.setForeground(new java.awt.Color(255, 255, 255));
        Capacidadlbl.setText("Capacidad máxima");

        TipoClaseTxt.setBackground(new java.awt.Color(204, 204, 204));
        TipoClaseTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TipoClaseTxt.setForeground(new java.awt.Color(51, 51, 51));
        TipoClaseTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TipoClaseTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoClaseTxtActionPerformed(evt);
            }
        });

        CapacidadTxt.setBackground(new java.awt.Color(204, 204, 204));
        CapacidadTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde", "Noche" }));

        EntrenadorTxt.setBackground(new java.awt.Color(204, 204, 204));
        EntrenadorTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        IdTxt.setBackground(new java.awt.Color(204, 204, 204));
        IdTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));

        IdLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        IdLbl.setForeground(new java.awt.Color(255, 255, 255));
        IdLbl.setText("Id:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(IdLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EntrenadorLbl)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoClaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoClaseLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntrenadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Capacidadlbl)
                            .addComponent(CapacidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HorarioRLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EntrenadorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EntrenadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(CapacidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Capacidadlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipoClaseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TipoClaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(HorarioRLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("                                                            Administrar Clases");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoClaseTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoClaseTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoClaseTxtActionPerformed

    private void AddLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLblMouseClicked
             DisableorActiveAll(true);
             this.IdLbl.setEnabled(false);
             this.IdLbl.setVisible(false);
             this.IdTxt.setEnabled(false);
             this.IdTxt.setVisible(false);

             

            
              jComboBox1.addItem("Mañana");
              jComboBox1.addItem("Tarde");
              jComboBox1.addItem("Noche");


    }//GEN-LAST:event_AddLblMouseClicked


    private void DeletelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletelblMouseClicked
         jComboBox1.removeAllItems();
        ClearTxt();
        DisableorActiveAll(false);
         this.IdLbl.setText("Ingrese el id de clase para eliminar");
          this.IdLbl.setEnabled(true);
        this.IdLbl.setVisible(true);
        this.IdTxt.setEnabled(true);
        this.IdTxt.setVisible(true);
    }//GEN-LAST:event_DeletelblMouseClicked

    private void ActualizarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarLblMouseClicked
         jComboBox1.removeAllItems();
        ClearTxt();
        DisableorActiveAll(false);
          jComboBox1.addItem("Mañana");
          jComboBox1.addItem("Tarde");
          jComboBox1.addItem("Noche");

        this.TipoClaseLbl.setEnabled(true);
        this.TipoClaseLbl.setVisible(true);
        this.TipoClaseTxt.setEnabled(true);
        this.TipoClaseTxt.setVisible(true); 
        this.EntrenadorLbl.setText("Nuevo Entrenador:");
        this.EntrenadorLbl.setEnabled(true);
        this.EntrenadorLbl.setVisible(true);
        this.EntrenadorTxt.setEnabled(true);
        this.EntrenadorTxt.setVisible(true);
        this.Capacidadlbl.setText("Capacidad:");
        this.Capacidadlbl.setEnabled(true);
        this.Capacidadlbl.setVisible(true);
        this.CapacidadTxt.setEnabled(true);
        this.CapacidadTxt.setVisible(true);      
     this.HorarioRLbl.setEnabled(true);
        this.HorarioRLbl.setVisible(true);
        this.jComboBox1.setEnabled(true);
        this.jComboBox1.setVisible(true);
       
    }//GEN-LAST:event_ActualizarLblMouseClicked

    private void BuscarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarLblMouseClicked
         jComboBox1.removeAllItems();
        ClearTxt();
        DisableorActiveAll(false);
        this.TipoClaseLbl.setText("Ingrese el id de clase a buscar:");
        this.TipoClaseLbl.setEnabled(true);
        this.TipoClaseLbl.setVisible(true);
        this.IdTxt.setEnabled(true);
        this.IdTxt.setText("");
        this.IdTxt.setVisible(true);           
    }//GEN-LAST:event_BuscarLblMouseClicked

    private void listoLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listoLblMouseClicked

        if (this.TipoClaseTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ningun campo  puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if (this.EntrenadorTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ningun campo  puede estar vacío..", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if (this.CapacidadTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ningun campo  puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if (this.jComboBox1.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Ningun campo  puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if (this.IdTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ningun campo  puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        
        if (!this.TipoClaseTxt.getText().isEmpty()
                && !this.EntrenadorTxt.getText().isEmpty() && !this.CapacidadTxt.getText().isEmpty()) {

            try {
                
                 int idEntrenador = Integer.parseInt(this.EntrenadorTxt.getText());
                if(daoentrenador.validatePk(idEntrenador)){
               
                Clase cls = new Clase(this.TipoClaseTxt.getText(),
                                      this.jComboBox1.getSelectedItem().toString(),
                        Integer.parseInt(this.EntrenadorTxt.getText()),
                        Integer.parseInt(this.CapacidadTxt.getText()));
                        dao.create(mapper.toDTO(cls));
                       ClearTxt();
                       DisableorActiveAll(false);
                }else{
              JOptionPane.showMessageDialog(null, "El entrenador no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);

                }
                
            } catch (SQLException ex) {
                Logger.getLogger(GUIClases.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            

        
        }
        else if (this.TipoClaseLbl.getText().equals("Ingrese el id de clase a buscar:")) {

            Clase cls;
            try {
                if (dao.validatePk(Integer.parseInt(this.IdTxt.getText()))){
                cls = mapper.toEnt(dao.read(Integer.valueOf(this.IdTxt.getText())));
                TipoClaseTxt.setText(cls.getTipoClase());
                 jComboBox1.addItem(cls.getHorario());
                EntrenadorTxt.setText(String.valueOf(cls.getIdEntrenador()));
                CapacidadTxt.setText(String.valueOf(cls.getCapacidadMaxima()));
                
                }else {
               JOptionPane.showMessageDialog(null, "La Clase no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
                } 
            } catch (SQLException ex) {
                Logger.getLogger(GUIClases.class.getName()).log(Level.SEVERE, null, ex);
            }
            DisableorActiveAll(true);

        } else if (this.IdLbl.getText().equals("Ingrese el id de clase para eliminar")) {
            System.out.println("x");
            try {
                if (dao.validatePk(Integer.parseInt(this.IdTxt.getText()))) {
                    
                    dao.delete(Integer.valueOf(IdTxt.getText()));
                    ClearTxt();
                    
                } else {
                    JOptionPane.showMessageDialog(null, "La clase no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
                  
                }
            } catch (SQLException ex) {
                Logger.getLogger(GUIClases.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

            try {
                if (dao.validatePk(Integer.parseInt(this.IdTxt.getText()))) {
                    Clase cls = new Clase (Integer.parseInt(IdTxt.getText()),TipoClaseTxt.getText(),jComboBox1.getSelectedItem().toString(),
                            Integer.parseInt(EntrenadorTxt.getText()),Integer.parseInt(CapacidadTxt.getText()));
                    dao.update(mapper.toDTO(cls));
                      DisableorActiveAll(false);
                    
                } else {
                    JOptionPane.showMessageDialog(null, "La clase no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(GUIClases.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
             
    }//GEN-LAST:event_listoLblMouseClicked

    private void CancelLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelLblMouseClicked
        // TODO add your handling code here:
        ClearTxt();
        DisableorActiveAll(false);
    }//GEN-LAST:event_CancelLblMouseClicked
      
        
   
    
public void DisableorActiveAll(boolean bool){
        this.TipoClaseLbl.setEnabled(bool);
        this.TipoClaseLbl.setVisible(bool);
        this.EntrenadorLbl.setEnabled(bool);
       this.EntrenadorLbl.setVisible(bool);
       this.Capacidadlbl.setEnabled(bool);
       this.Capacidadlbl.setVisible(bool);
       this.IdLbl.setEnabled(bool);
       this.IdLbl.setVisible(bool);
       this.HorarioRLbl.setEnabled(bool);
       this.HorarioRLbl.setVisible(bool);
        this.TipoClaseTxt.setEnabled(bool);
        this.TipoClaseTxt.setVisible(bool);
         this.jComboBox1.setEnabled(bool);
        this.jComboBox1.setVisible(bool);
        this.EntrenadorTxt.setEnabled(bool);
        this.EntrenadorTxt.setVisible(bool);
        this.CapacidadTxt.setEnabled(bool);
        this.CapacidadTxt.setVisible(bool);
        this.IdTxt.setEnabled(bool);
        this.IdTxt.setVisible(bool);
}

public void ClearTxt(){
   this.TipoClaseTxt.setText("");
   this.EntrenadorTxt.setText("");
   this.CapacidadTxt.setText("");
   this.IdTxt.setText("");
}

  public void showError(String err) {
        JOptionPane.showMessageDialog(this, err, "Error", JOptionPane.ERROR_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualizarLbl;
    private javax.swing.JLabel AddLbl;
    private javax.swing.JLabel BuscarLbl;
    private javax.swing.JLabel CancelLbl;
    private javax.swing.JFormattedTextField CapacidadTxt;
    private javax.swing.JLabel Capacidadlbl;
    private javax.swing.JLabel Deletelbl;
    private javax.swing.JLabel EntrenadorLbl;
    private javax.swing.JFormattedTextField EntrenadorTxt;
    private javax.swing.JLabel HorarioRLbl;
    private javax.swing.JLabel IdLbl;
    private javax.swing.JFormattedTextField IdTxt;
    private javax.swing.JLabel TipoClaseLbl;
    private javax.swing.JTextField TipoClaseTxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel listoLbl;
    // End of variables declaration//GEN-END:variables
}
