/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

//import Clientes.ListaCliente;
//import Paquetes.ListaPaquete;
//import Paquetes.Paquete;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Saliim
 */
public class GUIClases extends javax.swing.JInternalFrame {

    /**
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        AddLbl = new javax.swing.JLabel();
        Deletelbl = new javax.swing.JLabel();
        ActualizarLbl = new javax.swing.JLabel();
        BuscarLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CancelLbl = new javax.swing.JLabel();
        listoLbl = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        CedulaRLbl = new javax.swing.JLabel();
        DescripcionLbl = new javax.swing.JLabel();
        PesoLbl = new javax.swing.JLabel();
        CedulaDlbl = new javax.swing.JLabel();
        PesoTxt = new javax.swing.JFormattedTextField();
        TipoclaseTxt = new javax.swing.JTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(840, 421));

        jPanel6.setBackground(new java.awt.Color(33, 37, 41));

        AddLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AddLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-new-24.png"))); // NOI18N
        AddLbl.setText("Agregar");
        AddLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLblMouseClicked(evt);
            }
        });

        Deletelbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Deletelbl.setForeground(new java.awt.Color(255, 255, 255));
        Deletelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-cancelar-24.png"))); // NOI18N
        Deletelbl.setText("Eliminar");
        Deletelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletelblMouseClicked(evt);
            }
        });

        ActualizarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ActualizarLbl.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-crear-nuevo-24.png"))); // NOI18N
        ActualizarLbl.setText("Actualizar");
        ActualizarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarLblMouseClicked(evt);
            }
        });

        BuscarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BuscarLbl.setForeground(new java.awt.Color(255, 255, 255));
        BuscarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-google-web-search-24.png"))); // NOI18N
        BuscarLbl.setText("Buscar");
        BuscarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarLblMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Opciones ");

        CancelLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-delete-24.png"))); // NOI18N
        CancelLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelLblMouseClicked(evt);
            }
        });

        listoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-casilla-de-verificación-marcada-24.png"))); // NOI18N
        listoLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listoLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Deletelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(listoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Deletelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ActualizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BuscarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setOpaque(true);

        CedulaRLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CedulaRLbl.setForeground(new java.awt.Color(255, 255, 255));
        CedulaRLbl.setText("Horario:");

        DescripcionLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DescripcionLbl.setForeground(new java.awt.Color(255, 255, 255));
        DescripcionLbl.setText("Tipo de clase:");

        PesoLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PesoLbl.setForeground(new java.awt.Color(255, 255, 255));
        PesoLbl.setText("Entrenador Asignado:");

        CedulaDlbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CedulaDlbl.setForeground(new java.awt.Color(255, 255, 255));
        CedulaDlbl.setText("Capacidad máxima");

        PesoTxt.setBackground(new java.awt.Color(204, 204, 204));
        PesoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PesoTxt.setForeground(new java.awt.Color(51, 51, 51));
        PesoTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        PesoTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        TipoclaseTxt.setBackground(new java.awt.Color(204, 204, 204));
        TipoclaseTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TipoclaseTxt.setForeground(new java.awt.Color(51, 51, 51));
        TipoclaseTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TipoclaseTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoclaseTxtActionPerformed(evt);
            }
        });

        jFormattedTextField6.setBackground(new java.awt.Color(204, 204, 204));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde", "Noche" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(DescripcionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PesoLbl)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CedulaRLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CedulaDlbl)
                                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(TipoclaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescripcionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoclaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(CedulaRLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CedulaDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-paquete-24_2.png"))); // NOI18N
        jLabel1.setText("                                                            Administrar Clases");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoclaseTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoclaseTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoclaseTxtActionPerformed

    private void AddLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLblMouseClicked
     
    }//GEN-LAST:event_AddLblMouseClicked


    private void DeletelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletelblMouseClicked
         
    
        
    }//GEN-LAST:event_DeletelblMouseClicked

    private void ActualizarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarLblMouseClicked
      
    }//GEN-LAST:event_ActualizarLblMouseClicked

    private void BuscarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarLblMouseClicked
        // TODO add your handling code here:     
                    
    }//GEN-LAST:event_BuscarLblMouseClicked

    private void listoLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listoLblMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_listoLblMouseClicked

    private void CancelLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelLblMouseClicked
        // TODO add your handling code here:
        Clear();
        DisableorActiveAllP(false);
    }//GEN-LAST:event_CancelLblMouseClicked
      
        
    public void ListoFunc(){
//          if(!this.CodigoTxt.getText().isEmpty()&&!this.DescripcionTxt.getText().isEmpty()&&!this.PesoTxt.getText().isEmpty()
//                       &&!this.CedulaDTxt.getText().isEmpty()&&!this.CedulaRTxt.getText().isEmpty()){
//                   Paquete p = new Paquete(CodigoTxt.getText(),DescripcionTxt.getText(),PesoTxt.getText()
//                   ,CedulaDTxt.getText(),CedulaRTxt.getText());
//                   listP.agregarPaquete(p); 
//                   listC.SearchCliente(cedula).getPaquetes().agregarPaquete(p);
//                   Clear();
//                   DisableorActiveAllP(false);
//               }else if(this.CodigoLbl.equals("ingrese el codigo del paquete a eliminar:")){
//        
//                   if(!this.CodigoTxt.getText().isEmpty()){
//                       
//                       if(listP.buscarPaquete(this.CodigoTxt.getText())!=null){
//                           if(!listP.buscarPaquete(this.CodigoTxt.getText()).getEstado().equals("Transito")){
//                               try {
//                                   listP.eliminarPaquete(CodigoTxt.getText());
//                                    listC.SearchCliente(cedula).getPaquetes().eliminarPaquete(CodigoTxt.getText());
//                                     DisableorActiveAllP(false);
//                                          Clear();
//                               } catch (Exception ex) {
//                                   Logger.getLogger(FrmPaquetes.class.getName()).log(Level.SEVERE, null, ex);
//                               }
//                       }else{
//                                JOptionPane.showMessageDialog(null, "No se puede eliminar un paquete que este en transito", "Alerta", JOptionPane.WARNING_MESSAGE);
//                           }
//                   }else{
//                        JOptionPane.showMessageDialog(null, "Codigo no existente, intente de nuevo o el campo esta vacio", "Alerta", JOptionPane.WARNING_MESSAGE);
//                            this.CodigoTxt.setText("");
//                   }
//               }   
//           
//               }else if(this.CodigoLbl.getText().equals("ingrese el codigo del paquete para buscar:")){ 
//                 
//                   Paquete p = listP.buscarPaquete(this.CodigoTxt.getText());
//                   if(p!=null){
//                       DisableorActiveAllP(true);
//                       this.CodigoTxt.setText(p.getCodigo());
//                       this.DescripcionTxt.setText(p.getDescripcion());
//                       this.CedulaRTxt.setText(p.getRemitente());
//                       this.CedulaDTxt.setText(p.getDestinatario());
//                       
//                        this.PesoTxt.setText(String.valueOf(p.getPeso()));
//                       
//                   }else{
//                        JOptionPane.showMessageDialog(null, "Codigo no existente, intente de nuevo o el campo esta vacio", "Alerta", JOptionPane.WARNING_MESSAGE);
//                        this.CodigoTxt.setText("");
//                   }
//               }else{
//                   if(!this.CodigoTxt.getText().isEmpty()&&!this.CedulaRTxt.getText().isEmpty()&&!this.DescripcionTxt.getText().isEmpty()){
//                       listP.buscarPaquete(CodigoTxt.getText()).setDescripcion(DescripcionTxt.getText());
//                       listP.buscarPaquete(CodigoTxt.getText()).setDestinatario(CedulaRTxt.getText());
//                       Clear();
//                        DisableorActiveAllP(false);
//                   }else{
//                         JOptionPane.showMessageDialog(null, "Para actualizar los campos no pueden estar vacios intente de nuevo", "Alerta", JOptionPane.WARNING_MESSAGE);
//                   }
//               }
    }
public void DisableorActiveAllP(boolean x){
//     this.CodigoLbl.setText("Codigo:");
//     this.CedulaRLbl.setText("Cedula del Remitente:");
//    this.CodigoLbl.setEnabled(x);
//     this.CodigoLbl.setVisible(x);
//    this.CodigoTxt.setEnabled(x);
//    this.CodigoTxt.setVisible(x);
//    this.DescripcionLbl.setEnabled(x);
//    this.DescripcionLbl.setVisible(x);
//    this.DescripcionTxt.setEnabled(x);
//    this.DescripcionTxt.setVisible(x);
//    this.DescripcionTxt.setEnabled(x);
//    this.DescripcionTxt.setVisible(x);
//     this.PesoLbl.setEnabled(x);
//    this.PesoLbl.setVisible(x);
//    this.PesoTxt.setEnabled(x);
//    this.PesoTxt.setVisible(x);
//    this.CedulaRLbl.setEnabled(x);
//    this.CedulaRLbl.setVisible(x);
//    this.CedulaRTxt.setEnabled(x);
//    this.CedulaRTxt.setVisible(x);
//    this.CedulaDlbl.setEnabled(x);
//    this.CedulaDlbl.setVisible(x);
//     this.CedulaDTxt.setEnabled(x);
//    this.CedulaDTxt.setVisible(x);
//  
}

public void Clear(){
//    this.CodigoTxt.setText("");
//    this.DescripcionTxt.setText("");
//    this.CedulaRTxt.setText("");
//    this.CedulaDTxt.setText("");
//    this.PesoTxt.setText("");
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualizarLbl;
    private javax.swing.JLabel AddLbl;
    private javax.swing.JLabel BuscarLbl;
    private javax.swing.JLabel CancelLbl;
    private javax.swing.JLabel CedulaDlbl;
    private javax.swing.JLabel CedulaRLbl;
    private javax.swing.JLabel Deletelbl;
    private javax.swing.JLabel DescripcionLbl;
    private javax.swing.JLabel PesoLbl;
    private javax.swing.JFormattedTextField PesoTxt;
    private javax.swing.JTextField TipoclaseTxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel listoLbl;
    // End of variables declaration//GEN-END:variables
}
