/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import java.sql.SQLException;
import DataBase.DataBaseConnection;
import Model.Entrenador.Entrenador;
import Model.Entrenador.EntrenadorDAO;
import Model.Entrenador.EntrenadorMapper;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class GUIEntrenador extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEmpleados
     */
    private EntrenadorDAO dao;
    private final EntrenadorMapper mapper;

    public GUIEntrenador() {
        initComponents();
        DisableorActiveAll(false);
        try {
            dao = new EntrenadorDAO(DataBaseConnection.getConnection());
        } catch (SQLException ex) {
            //showError("Error al conectar con la Base de Datos");
        }
        mapper = new EntrenadorMapper();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AddLbl = new javax.swing.JLabel();
        buscarLbl = new javax.swing.JLabel();
        DeleteLbl = new javax.swing.JLabel();
        ActualizarLbl = new javax.swing.JLabel();
        ListoLbl = new javax.swing.JButton();
        CancelLbl = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        CedulaLbl = new javax.swing.JLabel();
        CedulaTxt = new javax.swing.JTextField();
        NombreLbl = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        TelLbl = new javax.swing.JLabel();
        EspecialidadTxt = new javax.swing.JTextField();
        PuestoLbl = new javax.swing.JLabel();
        BienestarBox = new javax.swing.JCheckBox();
        FuncionalBox = new javax.swing.JCheckBox();
        PersonalBox = new javax.swing.JCheckBox();
        NutricionBox = new javax.swing.JCheckBox();
        FuerzaBox = new javax.swing.JCheckBox();
        RehabilitacionBox = new javax.swing.JCheckBox();
        TelTxt1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setPreferredSize(new java.awt.Dimension(840, 421));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("                                                             Entrenadores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(33, 37, 41));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Opciones");

        AddLbl.setBackground(new java.awt.Color(255, 255, 255));
        AddLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AddLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddLbl.setText(" Agregar ");
        AddLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLblMouseClicked(evt);
            }
        });

        buscarLbl.setBackground(new java.awt.Color(255, 255, 255));
        buscarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buscarLbl.setForeground(new java.awt.Color(255, 255, 255));
        buscarLbl.setText("Buscar");
        buscarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarLblMouseClicked(evt);
            }
        });

        DeleteLbl.setBackground(new java.awt.Color(255, 255, 255));
        DeleteLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        DeleteLbl.setForeground(new java.awt.Color(255, 255, 255));
        DeleteLbl.setText("Eliminar");
        DeleteLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteLblMouseClicked(evt);
            }
        });

        ActualizarLbl.setBackground(new java.awt.Color(255, 255, 255));
        ActualizarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ActualizarLbl.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarLbl.setText("Actualizar");
        ActualizarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarLblMouseClicked(evt);
            }
        });

        ListoLbl.setBackground(new java.awt.Color(33, 37, 41));
        ListoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-casilla-de-verificación-marcada-24.png"))); // NOI18N
        ListoLbl.setBorderPainted(false);
        ListoLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListoLblActionPerformed(evt);
            }
        });

        CancelLbl.setBackground(new java.awt.Color(33, 37, 41));
        CancelLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancelar-24.png"))); // NOI18N
        CancelLbl.setBorderPainted(false);
        CancelLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelLblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DeleteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ActualizarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(ListoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(DeleteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ActualizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        CedulaLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CedulaLbl.setForeground(new java.awt.Color(153, 153, 153));
        CedulaLbl.setText("Id:");

        CedulaTxt.setBackground(new java.awt.Color(204, 204, 204));
        CedulaTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CedulaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaTxtActionPerformed(evt);
            }
        });

        NombreLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NombreLbl.setForeground(new java.awt.Color(153, 153, 153));
        NombreLbl.setText("Nombre:");

        NombreTxt.setBackground(new java.awt.Color(204, 204, 204));
        NombreTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });

        TelLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TelLbl.setForeground(new java.awt.Color(153, 153, 153));
        TelLbl.setText("Telefono:");

        EspecialidadTxt.setBackground(new java.awt.Color(204, 204, 204));
        EspecialidadTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EspecialidadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadTxtActionPerformed(evt);
            }
        });

        PuestoLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PuestoLbl.setForeground(new java.awt.Color(153, 153, 153));
        PuestoLbl.setText("Especialidades:");

        BienestarBox.setBackground(new java.awt.Color(153, 153, 153));
        BienestarBox.setForeground(new java.awt.Color(0, 0, 0));
        BienestarBox.setText("Bienestar");
        BienestarBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BienestarBoxActionPerformed(evt);
            }
        });

        FuncionalBox.setBackground(new java.awt.Color(153, 153, 153));
        FuncionalBox.setForeground(new java.awt.Color(0, 0, 0));
        FuncionalBox.setText("Funcional");

        PersonalBox.setBackground(new java.awt.Color(153, 153, 153));
        PersonalBox.setForeground(new java.awt.Color(0, 0, 0));
        PersonalBox.setText("Personal");

        NutricionBox.setBackground(new java.awt.Color(153, 153, 153));
        NutricionBox.setForeground(new java.awt.Color(0, 0, 0));
        NutricionBox.setText("Nutrición");

        FuerzaBox.setBackground(new java.awt.Color(153, 153, 153));
        FuerzaBox.setForeground(new java.awt.Color(0, 0, 0));
        FuerzaBox.setText("Fuerza");

        RehabilitacionBox.setBackground(new java.awt.Color(153, 153, 153));
        RehabilitacionBox.setForeground(new java.awt.Color(0, 0, 0));
        RehabilitacionBox.setText("Rehabilitación");
        RehabilitacionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RehabilitacionBoxActionPerformed(evt);
            }
        });

        TelTxt1.setBackground(new java.awt.Color(204, 204, 204));
        TelTxt1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TelTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelTxt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(NombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(92, 92, 92))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(77, 77, 77))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(CedulaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(CedulaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TelTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EspecialidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PersonalBox)
                                            .addComponent(FuncionalBox)
                                            .addComponent(FuerzaBox))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NutricionBox)
                                            .addComponent(BienestarBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RehabilitacionBox))
                                        .addGap(62, 62, 62))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(PuestoLbl)
                                        .addGap(124, 124, 124)))
                                .addGap(34, 34, 34)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(CedulaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(CedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(NombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(PuestoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BienestarBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PersonalBox))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FuncionalBox)
                                    .addComponent(RehabilitacionBox))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FuerzaBox)
                                    .addComponent(NutricionBox))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(EspecialidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TelTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CedulaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaTxtActionPerformed

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void EspecialidadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspecialidadTxtActionPerformed

    private void AddLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLblMouseClicked
        // TODO add your handling code here:
        DisableorActiveAll(true);
    }//GEN-LAST:event_AddLblMouseClicked

    private void buscarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarLblMouseClicked
        // TODO add your handling code here:
        ClearTxt();
        DisableorActiveAll(false);
        this.CedulaLbl.setText("Ingrese la Cedula para buscar:");
        this.CedulaLbl.setEnabled(true);
        this.CedulaLbl.setVisible(true);
        this.CedulaTxt.setEnabled(true);
        this.CedulaTxt.setText("");
        this.CedulaTxt.setVisible(true);
    }//GEN-LAST:event_buscarLblMouseClicked

    private void DeleteLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteLblMouseClicked
        // TODO add your handling code here:
        ClearTxt();
        DisableorActiveAll(false);
        this.CedulaLbl.setText("Ingrese la Cedula para eliminar");
        this.CedulaLbl.setEnabled(true);
        this.CedulaLbl.setVisible(true);
        this.CedulaTxt.setEnabled(true);
        this.CedulaTxt.setVisible(true);
    }//GEN-LAST:event_DeleteLblMouseClicked

    private void ActualizarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarLblMouseClicked
        ClearTxt();
        DisableorActiveAll(false);
        this.CedulaLbl.setEnabled(true);
        this.CedulaLbl.setVisible(true);
        this.CedulaTxt.setEnabled(true);
        this.CedulaTxt.setVisible(true);
        this.TelLbl.setText("Nuevo Telefono:");
        this.TelLbl.setEnabled(true);
        this.TelLbl.setVisible(true);
        this.EspecialidadTxt.setEnabled(true);
        this.EspecialidadTxt.setVisible(true);
        this.PuestoLbl.setText("Nueva Especialidad:");
        this.PuestoLbl.setEnabled(true);
        this.PuestoLbl.setVisible(true);
//        this.EspecialidadTxt.setEnabled(true);
//        this.EspecialidadTxt.setVisible(true);

    }//GEN-LAST:event_ActualizarLblMouseClicked

    private void ListoLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListoLblActionPerformed

        if (!this.NombreTxt.getText().isEmpty()
                && !this.EspecialidadTxt.getText().isEmpty()
                && alMenosUnCheckboxSeleccionado(PersonalBox, BienestarBox, FuncionalBox, RehabilitacionBox, FuerzaBox, NutricionBox)) {

            try {
                String especialidadesSeleccionadas = obtenerEspecialidadesSeleccionadas(PersonalBox, BienestarBox, FuncionalBox, RehabilitacionBox, FuerzaBox, NutricionBox);
                Entrenador emp = new Entrenador(
                        this.NombreTxt.getText(),
                        this.EspecialidadTxt.getText(),
                        especialidadesSeleccionadas);

                dao.create(mapper.toDTO(emp));
                ClearTxt();
                DisableorActiveAll(false);

            } catch (SQLException ex) {
                Logger.getLogger(GUIEntrenador.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (this.CedulaLbl.getText().equals("Ingrese la Cedula para buscar:")) {

            Entrenador emp;

            try {
                if (dao.validatePk(Integer.parseInt(this.CedulaTxt.getText()))) {
                    emp = mapper.toEnt(dao.read(Integer.valueOf(this.CedulaTxt.getText())));
                    CedulaTxt.setText(String.valueOf(emp.getId()));
                    NombreTxt.setText(emp.getNombre());
                    EspecialidadTxt.setText(emp.getContacto());
                    EspecialidadTxt.setText(emp.getEspecialidades());

                } else {
                    JOptionPane.showMessageDialog(null, "El cliente no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            DisableorActiveAll(true);

        } else if (this.CedulaLbl.getText().equals("Ingrese la Cedula para eliminar")) {

            try {
                if (dao.validatePk(Integer.parseInt(this.CedulaTxt.getText()))) {

                    dao.delete(Integer.valueOf(CedulaTxt.getText()));
                    ClearTxt();

                } else {
                    JOptionPane.showMessageDialog(null, "El cliente no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);

                }
            } catch (SQLException ex) {
                Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

            try {

                if (dao.validatePk(Integer.parseInt(this.CedulaTxt.getText()))) {
                    String especialidadesSeleccionadas = obtenerEspecialidadesSeleccionadas(PersonalBox, BienestarBox, FuncionalBox, RehabilitacionBox, FuerzaBox, NutricionBox);

                    Entrenador entrenador = new Entrenador(Integer.parseInt(
                            CedulaTxt.getText()),
                            NombreTxt.getText(),
                            EspecialidadTxt.getText(),
                            especialidadesSeleccionadas);
                    dao.update(mapper.toDTO(entrenador));
                    DisableorActiveAll(false);

                } else {
                    JOptionPane.showMessageDialog(null, "El cliente no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ListoLblActionPerformed

    private void CancelLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelLblActionPerformed
        // TODO add your handling code here:
        DisableorActiveAll(false);
        ClearTxt();
    }//GEN-LAST:event_CancelLblActionPerformed

    private void BienestarBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BienestarBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BienestarBoxActionPerformed

    private void RehabilitacionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RehabilitacionBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RehabilitacionBoxActionPerformed

    private void TelTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelTxt1ActionPerformed
    public static String obtenerEspecialidadesSeleccionadas(JCheckBox PersonalBox, JCheckBox BienestarBox, JCheckBox FuncionalBox, JCheckBox RehabilitacionBox, JCheckBox FuerzaBox, JCheckBox NutricionBox) {
        StringBuilder seleccionadas = new StringBuilder();

        JCheckBox[] checkBoxes = {
            PersonalBox, BienestarBox, FuncionalBox, RehabilitacionBox, FuerzaBox, NutricionBox
        };

        for (JCheckBox checkBox : checkBoxes) {
            if (checkBox.isSelected()) {
                if (seleccionadas.length() > 0) {
                    seleccionadas.append(", ");
                }
                seleccionadas.append(checkBox.getText());
            }
        }

        return seleccionadas.toString();
    }

    public void DisableorActiveAll(boolean bool) {
        //    this.CedulaLbl.setText("Cedula:");
        //        this.CorreoLbl.setText("Correo:");
        //       this.NombreLbl.setText("Nombre:");
        //          this.FechaNLbl.setText("Fecha N:");
        //    this.CedulaLbl.setEnabled(bool);
        //    this.CedulaLbl.setVisible(bool);
        //    this.CedulaTxt.setEnabled(bool);
        //    this.CedulaTxt.setVisible(bool);
        //    this.NombreLbl.setEnabled(bool);
        //    this.NombreLbl.setVisible(bool);
        //    this.NombreTxt.setEnabled(bool);
        //    this.NombreTxt.setVisible(bool);
        //    this.FechaNLbl.setEnabled(bool);
        //    this.FechaNLbl.setVisible(bool);
        //    this.FechaNTxt.setEnabled(bool);
        //    this.FechaNTxt.setVisible(bool);
        //     this.CorreoLbl.setEnabled(bool);
        //    this.CorreoLbl.setVisible(bool);
        //    this.CorreoTxt.setEnabled(bool);
        //    this.CorreoTxt.setVisible(bool);
        //    this.TelLbl.setEnabled(bool);
        //    this.TelLbl.setVisible(bool);
        //    this.TelTxt.setEnabled(bool);
        //    this.TelTxt.setVisible(bool);
        //    this.PuestoLbl.setEnabled(bool);
        //    this.PuestoLbl.setVisible(bool);
        //    this.PuestoTxt.setEnabled(bool);
        //    this.PuestoTxt.setVisible(bool);
        //    this.SalarioLbl.setEnabled(bool);
        //    this.SalarioLbl.setVisible(bool);
        //    this.SalarioTxt.setEnabled(bool);
        //    this.SalarioTxt.setVisible(bool);
    }

    public void ClearTxt() {
        this.CedulaTxt.setText("");
        this.NombreTxt.setText("");
        this.EspecialidadTxt.setText("");
        this.EspecialidadTxt.setText("");

    }

    public void showError(String err) {
        JOptionPane.showMessageDialog(this, err, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private boolean alMenosUnCheckboxSeleccionado(JCheckBox... checkBoxes) {
        for (JCheckBox checkBox : checkBoxes) {
            if (checkBox.isSelected()) {
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualizarLbl;
    private javax.swing.JLabel AddLbl;
    private javax.swing.JCheckBox BienestarBox;
    private javax.swing.JButton CancelLbl;
    private javax.swing.JLabel CedulaLbl;
    private javax.swing.JTextField CedulaTxt;
    private javax.swing.JLabel DeleteLbl;
    private javax.swing.JTextField EspecialidadTxt;
    private javax.swing.JCheckBox FuerzaBox;
    private javax.swing.JCheckBox FuncionalBox;
    private javax.swing.JButton ListoLbl;
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JCheckBox NutricionBox;
    private javax.swing.JCheckBox PersonalBox;
    private javax.swing.JLabel PuestoLbl;
    private javax.swing.JCheckBox RehabilitacionBox;
    private javax.swing.JLabel TelLbl;
    private javax.swing.JTextField TelTxt1;
    private javax.swing.JLabel buscarLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
