/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

//import Empleados.Empleado;
//import RutasEntrega.ListaRutasEntrega;
//import RutasEntrega.RutaEntrega;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTextField;



/**
 *
 * @author PC
 */
public class GUILogin extends javax.swing.JInternalFrame {
/**
     * Creates new form FrmRutaEntrega
     */
//    private ListaRutasEntrega listR;
//    public FrmRutaEntrega() {
//        initComponents();
//         DisableorActiveAll(false);
//          listR= ListaRutasEntrega.getInstance();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CodigoLbl = new javax.swing.JLabel();
        UsuarioTxt = new javax.swing.JTextField();
        NombreLbl = new javax.swing.JLabel();
        ContraseñaTxt = new javax.swing.JTextField();
        DestinosLbl = new javax.swing.JLabel();
        RolesBox = new javax.swing.JComboBox<>();
        SiguienteLbl = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(840, 421));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-ruta-24.png"))); // NOI18N
        jLabel1.setText("Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CodigoLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CodigoLbl.setForeground(new java.awt.Color(255, 255, 255));
        CodigoLbl.setText("Usuario");

        UsuarioTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        UsuarioTxt.setForeground(new java.awt.Color(204, 204, 204));
        UsuarioTxt.setToolTipText("");
        UsuarioTxt.setBorder(null);
        UsuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTxtActionPerformed(evt);
            }
        });

        NombreLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NombreLbl.setForeground(new java.awt.Color(255, 255, 255));
        NombreLbl.setText("Contraseña");

        ContraseñaTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ContraseñaTxt.setForeground(new java.awt.Color(204, 204, 204));
        ContraseñaTxt.setBorder(null);
        ContraseñaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTxtActionPerformed(evt);
            }
        });

        DestinosLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DestinosLbl.setForeground(new java.awt.Color(255, 255, 255));
        DestinosLbl.setText("Roles");

        RolesBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        RolesBox.setForeground(new java.awt.Color(255, 255, 255));
        RolesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Entrenador" }));
        RolesBox.setToolTipText("");
        RolesBox.setName(""); // NOI18N

        SiguienteLbl.setBackground(new java.awt.Color(46, 62, 78));
        SiguienteLbl.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        SiguienteLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-casilla-de-verificación-marcada-24.png"))); // NOI18N
        SiguienteLbl.setText("Siguiente");
        SiguienteLbl.setBorderPainted(false);
        SiguienteLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SiguienteLblMouseClicked(evt);
            }
        });
        SiguienteLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteLblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(RolesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addComponent(UsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CodigoLbl))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreLbl)
                            .addComponent(ContraseñaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(SiguienteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(DestinosLbl)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(DestinosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RolesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SiguienteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTxtActionPerformed

    private void ContraseñaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTxtActionPerformed

    private void SiguienteLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiguienteLblMouseClicked
//         if(!this.CodigoTxt.getText().isEmpty()&&!this.NombreTxt.getText().isEmpty()&&!this.DescripcionTxt.getText().isEmpty()){
//           
//            
//            RutaEntrega emp = new RutaEntrega(this.CodigoTxt.getText(),
//           this.NombreTxt.getText(),this.DescripcionTxt.getText());
//            listR.agregarRuta(emp);
//             System.out.println( emp.getDescripcion());
//            emp.agregarDestino(addDestinoTxt.getText());
//            DestinoBox.addItem(addDestinoTxt.getText());
//               clearTxt();
//                DisableorActiveAll(false);
//             
//        }else if(this.NombreLbl.getText().equals("Descripcion:")){
//               if(!NombreTxt.getText().equals("")){
//               listR.buscarRuta(this.CodigoTxt.getText()).setDescripcion(this.NombreTxt.getText());
//               }
//               if(!addDestinoTxt.getText().equals("")){
//              listR.buscarRuta(this.CodigoTxt.getText()).agregarDestino(addDestinoTxt.getText());
//                DestinoBox.addItem(addDestinoTxt.getText());
//               }
//                DisableorActiveAll(false);
//                clearTxt();
//                
//        }else if(this.CodigoLbl.getText().equals("Ingrese Codigo para buscar:")){
//           
//            if(listR.buscarRuta(this.CodigoTxt.getText())!=null){
//            RutaEntrega emp = listR.buscarRuta(this.CodigoTxt.getText());
//            actualizarComboBox(emp.getDestinos());
//            this.CodigoTxt.setText(emp.getCodigo());
//            this.NombreTxt.setText(emp.getNombre());
//            this.DescripcionTxt.setText(emp.getDescripcion());
//            DisableorActiveAll(true);
//            agregarDestinoLbl.setEnabled(false);
//            agregarDestinoLbl.setVisible(false);
//            addDestinoTxt.setEnabled(false);
//            addDestinoTxt.setVisible(false);          
//            
//}else{
//                  JOptionPane.showMessageDialog(null, "Codigo correcto o inexistente intente ", "informacion incorrecta", JOptionPane.WARNING_MESSAGE); 
//              }
//          
//        }else if(this.CodigoLbl.getText().equals("Ingrese Codigo para eliminar:")){
//          
//            if(listR.buscarRuta(this.CodigoTxt.getText())!=null){
//            listR.eliminarRuta(this.CodigoTxt.getText());
//            }else{
//                JOptionPane.showMessageDialog(null, "La ruta no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE); 
//            }
//        }else{
//               if(listR.buscarRuta(this.CodigoTxt.getText())!=null){
//                   listR.buscarRuta(this.CodigoTxt.getText()).borrarDestinoString(String.valueOf(DestinoBox.getSelectedItem()));
//                    }else{
//                    JOptionPane.showMessageDialog(null, "La ruta no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE); 
//               }
//        }
    }//GEN-LAST:event_SiguienteLblMouseClicked

    private void SiguienteLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiguienteLblActionPerformed

public void DisableorActiveAll(boolean x){
//    this.CodigoLbl.setText("Codigo:");
//    this.NombreLbl.setText("Nombre:");
//    this.CodigoLbl.setEnabled(x);
//    this.CodigoLbl.setVisible(x);
//    this.usuariosTxt.setEnabled(x);
//    this.usuariosTxt.setVisible(x);
//    this.NombreLbl.setEnabled(x);
//    this.NombreLbl.setVisible(x);
//    this.contraseñaTxt.setEnabled(x);
//    this.contraseñaTxt.setVisible(x);
//    this.DescripcionLbl.setEnabled(x);
//    this.DescripcionLbl.setVisible(x);
//    this.DescripcionTxt.setEnabled(x);
//    this.DescripcionTxt.setVisible(x);
//     this.DestinosLbl.setEnabled(x);
//    this.DestinosLbl.setVisible(x);
//    this.RolesBox.setEnabled(x);
//    this.RolesBox.setVisible(x);
//    this.agregarDestinoLbl.setEnabled(x);
//    this.agregarDestinoLbl.setVisible(x);
//    this.addDestinoTxt.setEnabled(x);
//    this.addDestinoTxt.setVisible(x);
//    DestinosLbl.setEnabled(x);
//    DestinosLbl.setVisible(x);
  
}
 public void actualizarComboBox(Set<String> destinos) {
        // Limpiar el combo box
        this.RolesBox.removeAllItems();

        // Recorrer la lista de destinos y agregarlos al combo box
        for (String destino : destinos) {
            RolesBox.addItem(destino);
        }
    }
public void clearTxt(){
    UsuarioTxt.setText("");
    ContraseñaTxt.setText("");
//    DescripcionTxt.setText("");
//    addDestinoTxt.setText("");
   
   
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodigoLbl;
    private javax.swing.JTextField ContraseñaTxt;
    private javax.swing.JLabel DestinosLbl;
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JComboBox<String> RolesBox;
    private javax.swing.JButton SiguienteLbl;
    private javax.swing.JTextField UsuarioTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
