/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/*import Clientes.ListaCliente;
import Envios.Envio;
import Envios.GestionEnvios;
import Paquetes.ListaPaquete;
import Paquetes.Paquete;
import RutasEntrega.ListaRutasEntrega;
import RutasEntrega.RutaEntrega;
*/import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class GUIPagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEmpleados
     */
    /*private ListaPaquete listP;
    private ListaCliente listC;
    private GestionEnvios listE;
    private ListaRutasEntrega listR;*/
    public GUIPagos() {
        /*initComponents();
        DisableorActiveAll(false);
        listP = ListaPaquete.getInstance();
        listE = GestionEnvios.getInstance();
        listC = ListaCliente.getInstance();
       listR= ListaRutasEntrega.getInstance();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AddLbl = new javax.swing.JLabel();
        buscarLbl = new javax.swing.JLabel();
        ListoLbl = new javax.swing.JButton();
        CancelLbl = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        CedulaLbl = new javax.swing.JLabel();
        idpagotxt = new javax.swing.JTextField();
        FechaNLbl = new javax.swing.JLabel();
        CorreoLbl = new javax.swing.JLabel();
        IdClientetxt = new javax.swing.JTextField();
        SalarioLbl4 = new javax.swing.JLabel();
        FechaTxt = new javax.swing.JFormattedTextField();
        subtotaltxt = new javax.swing.JLabel();
        FechaNLbl3 = new javax.swing.JLabel();
        FechaETxt1 = new javax.swing.JFormattedTextField();
        impuestotxt = new javax.swing.JFormattedTextField();
        Totaltxt = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setPreferredSize(new java.awt.Dimension(840, 421));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));

        jPanel2.setBackground(new java.awt.Color(255, 206, 84));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagenes/icons8-trabajo-permanente-24.png"))); // NOI18N
        jLabel1.setText("                                                            Administrar Pagos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(33, 37, 41));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Opciones");

        AddLbl.setBackground(new java.awt.Color(255, 255, 255));
        AddLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AddLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-new-24.png"))); // NOI18N
        AddLbl.setText("Agregar");
        AddLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLblMouseClicked(evt);
            }
        });

        buscarLbl.setBackground(new java.awt.Color(255, 255, 255));
        buscarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buscarLbl.setForeground(new java.awt.Color(255, 255, 255));
        buscarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-google-web-search-24.png"))); // NOI18N
        buscarLbl.setText("Buscar");
        buscarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarLblMouseClicked(evt);
            }
        });

        ListoLbl.setBackground(new java.awt.Color(33, 37, 41));
        ListoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-casilla-de-verificación-marcada-24.png"))); // NOI18N
        ListoLbl.setBorderPainted(false);
        ListoLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListoLblMouseClicked(evt);
            }
        });
        ListoLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListoLblActionPerformed(evt);
            }
        });

        CancelLbl.setBackground(new java.awt.Color(33, 37, 41));
        CancelLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-24.png"))); // NOI18N
        CancelLbl.setBorderPainted(false);
        CancelLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelLblMouseClicked(evt);
            }
        });
        CancelLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelLblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addComponent(buscarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(AddLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel5.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        CedulaLbl.setBackground(new java.awt.Color(153, 153, 153));
        CedulaLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CedulaLbl.setForeground(new java.awt.Color(153, 153, 153));
        CedulaLbl.setText("Id de pago");

        idpagotxt.setEditable(false);
        idpagotxt.setBackground(new java.awt.Color(204, 204, 204));
        idpagotxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idpagotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpagotxtActionPerformed(evt);
            }
        });

        FechaNLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FechaNLbl.setForeground(new java.awt.Color(153, 153, 153));
        FechaNLbl.setText("Fecha:");

        CorreoLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CorreoLbl.setForeground(new java.awt.Color(153, 153, 153));
        CorreoLbl.setText(" Cliente:");

        IdClientetxt.setEditable(false);
        IdClientetxt.setBackground(new java.awt.Color(204, 204, 204));
        IdClientetxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        IdClientetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdClientetxtActionPerformed(evt);
            }
        });

        SalarioLbl4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SalarioLbl4.setForeground(new java.awt.Color(153, 153, 153));
        SalarioLbl4.setText("Total:");

        FechaTxt.setBackground(new java.awt.Color(204, 204, 204));
        FechaTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd MM yyyy"))));
        FechaTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FechaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaTxtActionPerformed(evt);
            }
        });

        subtotaltxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        subtotaltxt.setForeground(new java.awt.Color(153, 153, 153));
        subtotaltxt.setText("Subtotal:");

        FechaNLbl3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FechaNLbl3.setForeground(new java.awt.Color(153, 153, 153));
        FechaNLbl3.setText("Impuesto:");

        FechaETxt1.setBackground(new java.awt.Color(204, 204, 204));
        FechaETxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        FechaETxt1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FechaETxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaETxt1ActionPerformed(evt);
            }
        });

        impuestotxt.setBackground(new java.awt.Color(204, 204, 204));
        impuestotxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        impuestotxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        impuestotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impuestotxtActionPerformed(evt);
            }
        });

        Totaltxt.setBackground(new java.awt.Color(204, 204, 204));
        Totaltxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        Totaltxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotaltxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(subtotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(FechaNLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                            .addComponent(CedulaLbl)
                                            .addComponent(CorreoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FechaTxt)
                                            .addComponent(IdClientetxt)
                                            .addComponent(idpagotxt))
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(98, 98, 98)
                                                .addComponent(FechaNLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(SalarioLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(76, 76, 76))
                                                    .addComponent(FechaETxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Totaltxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(impuestotxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CedulaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idpagotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaETxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CorreoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaNLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FechaNLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SalarioLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(IdClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(impuestotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idpagotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpagotxtActionPerformed
        // TODO add your hhandling code here:
    }//GEN-LAST:event_idpagotxtActionPerformed

    private void IdClientetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdClientetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdClientetxtActionPerformed

    private void AddLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLblMouseClicked
        /*  this.ClearTxt();
        JTextField textField = new JTextField();
        Object[] message = {
            "Ingrese la cédula del cliente al que le pertenece el tramite:", textField
        };
        int option = JOptionPane.showConfirmDialog(null, message, "Entrada de Cédula", JOptionPane.OK_CANCEL_OPTION);
        String id = textField.getText();
        if((option == JOptionPane.OK_OPTION&&!textField.getText().isEmpty()&&this.listC.SearchCliente(id)!=null)){
        DisableorActiveAll(true);
        this.jComboBoxPaquete.removeAllItems();
        actualizarComboBoxP(this.listC.SearchCliente(id).getPaquetes().getPaquetesL());
        this.NumeroEnvioTxt.setText(String.valueOf(this.listE.getListaEnvios().size()+1));
        this.CedulaTxt.setText(id);
        this.NombreTxt.setText(this.listC.SearchCliente(id).getNombre());
        this.FechaETxt1.setText(String.valueOf(LocalDate.now()));
          actualizarComboBoxR(this.listR.getRutas());
          this.EstadoLbl.setVisible(false);
          this.EstadoTxt.setVisible(false);
        }else{
         JOptionPane.showMessageDialog(null, "Cédula no existente, intente de nuevo", "Alerta", JOptionPane.WARNING_MESSAGE);    
        }
    }//GEN-LAST:event_AddLblMouseClicked
 public void actualizarComboBoxR(HashSet<RutaEntrega> e) {
     
        for ( RutaEntrega es : e) {
            this.jComboBoxRuta.addItem(es.getCodigo());
        }
        
    }
  public void actualizarComboBoxP(HashMap<String,Paquete> e) {
     
        for ( Map.Entry<String, Paquete> entry : e.entrySet()) {
            this.jComboBoxPaquete.addItem(entry.getValue().getCodigo());
        }*/
        
    }
    private void buscarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarLblMouseClicked
        // TODO add your handling code here:
          DisableorActiveAll(false);
        this.CedulaLbl.setEnabled(true);
         this.CedulaLbl.setVisible(true);
          this.CedulaLbl.setText("Numero de Envio a Buscar");
           this.idpagotxt.setEditable(true);
        this.idpagotxt.setEnabled(true);
        this.idpagotxt.setVisible(true);
    }//GEN-LAST:event_buscarLblMouseClicked

    private void CancelLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelLblMouseClicked
this.ClearTxt();
this.DisableorActiveAll(false);

    }//GEN-LAST:event_CancelLblMouseClicked

    private void ListoLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListoLblMouseClicked
   
    }//GEN-LAST:event_ListoLblMouseClicked

    private void ListoLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListoLblActionPerformed
        // TODO add your handling code here:
//        if(NombreLbl.isVisible()){
//          try {
//              if( isFechaAntesDeHoy(this.FechaETxt.getText())){
//                  JOptionPane.showMessageDialog(null, "La fecha de entrega no puede ser anterior a la fecha actual", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
//              }else if(listC.SearchCliente(CedulaTxt.getText())==null){
//                  JOptionPane.showMessageDialog(null, "El cliente no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
//              }else{
//                  Envio envio  = new Envio(listC.SearchCliente(CedulaTxt.getText()),
//                          listP.buscarPaquete(jComboBoxPaquete.getSelectedItem().toString()),
//                          listR.buscarRuta(jComboBoxRuta.getSelectedItem().toString()),convertirStringAFecha(this.FechaETxt.getText()));
//                  System.out.println("entro a fecha envio "+this.FechaETxt.getText());
//                  System.out.println(envio.getRuta().getDescripcion());
//                  listE.registrarEnvio(envio);
//                 
//             
//                  JOptionPane.showMessageDialog(null, "Envio Registrado, Codigo : "+envio.getNumeroEnvio(), "A nombre del cliente: "+listC.SearchCliente(CedulaTxt.getText()).getNombre(), JOptionPane.WARNING_MESSAGE);
//                       this.ClearTxt();
//                  this.DisableorActiveAll(false); 
//              }
//          } catch (ParseException ex) {
//              Logger.getLogger(FrmEnvios.class.getName()).log(Level.SEVERE, null, ex);
//          }
//  }else if(CedulaLbl.getText().equals("Numero de Envio a Buscar")){
//       if(listE.buscarEnvio(Integer.parseInt(this.NumeroEnvioTxt.getText()))!=null){
//     
//            Envio envio = listE.buscarEnvio(Integer.parseInt(this.NumeroEnvioTxt.getText()));
//            this.NumeroEnvioTxt.setText(String.valueOf(envio.getNumeroEnvio()));
//            this.CedulaTxt.setText(envio.getCliente().getCedula());
//            this.NombreTxt.setText(envio.getCliente().getNombre());
//            FechaETxt.setText(String.valueOf(envio.getFechaEntrega()));
//            FechaETxt1.setText(String.valueOf(envio.getFechaEntrega()));
//            jComboBoxPaquete.addItem(envio.getPaquete().getCodigo());
//            jComboBoxRuta.addItem(envio.getRuta().getCodigo());
//            this.EstadoTxt.setText(envio.getEstado());
//            DisableorActiveAll(true);
//            }else{
//                JOptionPane.showMessageDialog(null, "El envio no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
//            }
//  }else if(CedulaLbl.getText().equals("Presione listo para despachar!")){
//                    if(this.listE.getCantidadEnviosNoNulosQ()>0){
//                   listE.despacharEnvio();
//              ClearTxt();
//               JOptionPane.showMessageDialog(null, "Envio Despachado!", "completado", JOptionPane.WARNING_MESSAGE);
//                    }else{
//                       JOptionPane.showMessageDialog(null, "El envio no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
//                    }
//  }else if (CedulaLbl.getText().equals("Numero de Envio a Entregar")){
//      if(listE.buscarEnvio(Integer.parseInt(NumeroEnvioTxt.getText()))!=null){
//            if(this.listE.getCantidadEnviosNoNulosQ()>0){
//       listE.entregarEnvio(Integer.parseInt(NumeroEnvioTxt.getText()));
//       ClearTxt();
//        JOptionPane.showMessageDialog(null, "Envio Entregado!", "completado", JOptionPane.WARNING_MESSAGE);
//            }else{
//            JOptionPane.showMessageDialog(null, "El envio no existe en la cola de envios", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
//            }
//  }else{
//       JOptionPane.showMessageDialog(null, "El envio no existe en la cola de envios", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
//  }
//  }else if(CedulaLbl.getText().equals("Numero de Envio a Cancelar")){
//      
//          if(listE.buscarEnvio(Integer.parseInt(NumeroEnvioTxt.getText()))!=null){
//              if(this.listE.getCantidadEnviosNoNulosQ()>0){
//       listE.cancelarEnvio(Integer.parseInt(NumeroEnvioTxt.getText()));
//       ClearTxt();
//        JOptionPane.showMessageDialog(null, "Envio Cancelado!", "completado", JOptionPane.WARNING_MESSAGE);
//              }else{
//                        JOptionPane.showMessageDialog(null, "El envio no existe en la cola de envios", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
//              }
//  }else{
//       JOptionPane.showMessageDialog(null, "El envio no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
//  } 
//  }*/
    }//GEN-LAST:event_ListoLblActionPerformed

    private void FechaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaTxtActionPerformed

    private void CancelLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelLblActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CancelLblActionPerformed

    private void FechaETxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaETxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaETxt1ActionPerformed

    private void impuestotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impuestotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_impuestotxtActionPerformed

    private void TotaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotaltxtActionPerformed

public void DisableorActiveAll(boolean bool){
//    this.CedulaLbl.setEnabled(bool);
//    this.CedulaLbl.setVisible(bool);
//    this.NumeroEnvioTxt.setEnabled(bool);
//    this.NumeroEnvioTxt.setVisible(bool);
//    this.NombreLbl.setEnabled(bool);
//    this.NombreLbl.setVisible(bool);
//    this.CedulaTxt.setEnabled(bool);
//    this.CedulaTxt.setVisible(bool);
//    this.FechaNLbl.setEnabled(bool);
//    this.FechaNLbl.setVisible(bool);
//    this.FechaETxt.setEnabled(bool);
//    this.FechaETxt.setVisible(bool);
//     this.CorreoLbl.setEnabled(bool);
//    this.CorreoLbl.setVisible(bool);
//    this.NombreTxt.setEnabled(bool);
//    this.NombreTxt.setVisible(bool);
//    this.SalarioLbl.setEnabled(bool);
//    this.SalarioLbl.setVisible(bool);
//    this.jComboBoxPaquete.setEnabled(bool);
//    this.jComboBoxPaquete.setVisible(bool);
//    this.SalarioLbl3.setEnabled(bool);
//    this.SalarioLbl3.setVisible(bool);
//    this.jComboBoxRuta.setEnabled(bool);
//    this.jComboBoxRuta.setVisible(bool);
//    this.SalarioLbl.setEnabled(bool);
//    this.SalarioLbl.setVisible(bool);
//    this.SalarioLbl4.setEnabled(bool);
//    this.SalarioLbl4.setVisible(bool);
//     this.PrecioTxt.setEnabled(bool);
//    this.PrecioTxt.setVisible(bool);
//    this.FechaNLbl1.setEnabled(bool);
//    this.FechaNLbl1.setVisible(bool);
//     this.FechaETxt1.setEnabled(bool);
//    this.FechaETxt1.setVisible(bool);
//    this.EstadoLbl.setVisible(bool);
//      this.EstadoLbl.setEnabled(bool);
//       this.EstadoTxt.setVisible(bool);
//      this.EstadoTxt.setEnabled(bool);
}

public void ClearTxt(){
//    this.NumeroEnvioTxt.setText("");
//    this.CedulaTxt.setText("");
//    this.NombreTxt.setText("");
//    this.FechaETxt.setText("");
//    this.PrecioTxt.setText("");
//    this.EstadoTxt.setText("");
//    this.jComboBoxPaquete.removeAllItems();
//    this.jComboBoxRuta.removeAllItems();
       
}
 public LocalDate convertirStringAFecha(String fechaStr) {
        try {
            if (fechaStr == null || fechaStr.isEmpty()) {
                throw new IllegalArgumentException("La fecha no puede estar vacía.");
            }
            
            // Especifica el formato de la fecha si es necesario
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
            
            // Intenta parsear el String a LocalDate
            return LocalDate.parse(fechaStr, formatter);
        } catch (DateTimeParseException e) {
            System.out.println("Error al parsear la fecha: " + e.getMessage());
            return null; // O manejar el error según sea necesario
        }
    }
  private double calcularPrecio1(double peso) {
        return 2100 + (peso > 1 ? (peso - 1) * 1200 : 0);
    }
  
   public static boolean isFechaAntesDeHoy(String fechaTexto) throws ParseException {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        try {
            // Verifica si el campo de texto no está vacío
            if (fechaTexto == null || fechaTexto.trim().isEmpty()) {
                throw new IllegalArgumentException("El campo de fecha está vacío.");
            }

            // Convierte el texto de la fecha a un objeto Date
            Date fechaIngresada = formatter.parse(fechaTexto);

            // Obtiene la fecha actual
            Date fechaActual = new Date();

            // Comprueba si la fecha ingresada es anterior a la fecha actual
            return fechaIngresada.before(fechaActual);

        }catch (IllegalArgumentException e) {
            // Maneja el caso de campo de texto vacío u otro error
            System.out.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "El campo de fecha no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        // Captura y maneja el error de parseo de la fecha
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLbl;
    private javax.swing.JButton CancelLbl;
    private javax.swing.JLabel CedulaLbl;
    private javax.swing.JLabel CorreoLbl;
    private javax.swing.JFormattedTextField FechaETxt1;
    private javax.swing.JLabel FechaNLbl;
    private javax.swing.JLabel FechaNLbl3;
    private javax.swing.JFormattedTextField FechaTxt;
    private javax.swing.JTextField IdClientetxt;
    private javax.swing.JButton ListoLbl;
    private javax.swing.JLabel SalarioLbl4;
    private javax.swing.JFormattedTextField Totaltxt;
    private javax.swing.JLabel buscarLbl;
    private javax.swing.JTextField idpagotxt;
    private javax.swing.JFormattedTextField impuestotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel subtotaltxt;
    // End of variables declaration//GEN-END:variables
}
