/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

//import Clientes.Cliente;
//import Clientes.ListaCliente;
//import Empleados.Empleado;
//import Empleados.ListaEmpleados;
//import Paquetes.ListaPaquete;
//import Paquetes.Paquete;
import DataBase.DataBaseConnection;
import Model.Cliente.Cliente;
import Model.Cliente.ClienteDAO;
import Model.Cliente.ClienteMapper;
import Model.Usuario.Usuario;
import Model.Usuario.UsuarioDAO;
import Model.Usuario.UsuarioMapper;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class GUIUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEmpleados
     */
    //private ListaCliente listE;
    private UsuarioDAO dao;
    private final UsuarioMapper mapper;

    public GUIUsuario() {
        initComponents();
        DisableorActiveAll(false);
        try {
            dao = new UsuarioDAO(DataBaseConnection.getConnection());
        } catch (SQLException ex) {
            showError("Error al conectar con la Base de Datos");
        }
        mapper = new UsuarioMapper();
        jComboBox1.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        AddLbl = new javax.swing.JLabel();
        buscarLbl = new javax.swing.JLabel();
        DeleteLbl = new javax.swing.JLabel();
        ActualizarLbl = new javax.swing.JLabel();
        ListoLbl = new javax.swing.JButton();
        CancelLbl = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        CedulaLbl = new javax.swing.JLabel();
        CedulaTxt1 = new javax.swing.JTextField();
        NombreLbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        TipoMembresiaLbl1 = new javax.swing.JLabel();
        CedulaTxt = new javax.swing.JFormattedTextField();
        CedulaLbl1 = new javax.swing.JLabel();
        NombreTxt1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Opciones");

        setPreferredSize(new java.awt.Dimension(840, 421));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));

        jPanel2.setBackground(new java.awt.Color(102, 204, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("                                                            Administrar Usuarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(33, 37, 41));

        AddLbl.setBackground(new java.awt.Color(255, 255, 255));
        AddLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AddLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddLbl.setText(" Agregar ");
        AddLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLblMouseClicked(evt);
            }
        });

        buscarLbl.setBackground(new java.awt.Color(255, 255, 255));
        buscarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buscarLbl.setForeground(new java.awt.Color(255, 255, 255));
        buscarLbl.setText("Buscar");
        buscarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarLblMouseClicked(evt);
            }
        });

        DeleteLbl.setBackground(new java.awt.Color(255, 255, 255));
        DeleteLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        DeleteLbl.setForeground(new java.awt.Color(255, 255, 255));
        DeleteLbl.setText("Eliminar");
        DeleteLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteLblMouseClicked(evt);
            }
        });

        ActualizarLbl.setBackground(new java.awt.Color(255, 255, 255));
        ActualizarLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ActualizarLbl.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarLbl.setText("Editar");
        ActualizarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarLblMouseClicked(evt);
            }
        });

        ListoLbl.setBackground(new java.awt.Color(33, 37, 41));
        ListoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-casilla-de-verificación-marcada-24.png"))); // NOI18N
        ListoLbl.setBorderPainted(false);
        ListoLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListoLblActionPerformed(evt);
            }
        });

        CancelLbl.setBackground(new java.awt.Color(33, 37, 41));
        CancelLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancelar-24.png"))); // NOI18N
        CancelLbl.setBorderPainted(false);
        CancelLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelLblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DeleteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ActualizarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(ListoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(AddLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(DeleteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ActualizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        CedulaLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CedulaLbl.setForeground(new java.awt.Color(153, 153, 153));
        CedulaLbl.setText("Id del Usuario:");

        CedulaTxt1.setBackground(new java.awt.Color(204, 204, 204));
        CedulaTxt1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CedulaTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaTxt1ActionPerformed(evt);
            }
        });

        NombreLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NombreLbl.setForeground(new java.awt.Color(153, 153, 153));
        NombreLbl.setText("Contraseña:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Entrenador" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        TipoMembresiaLbl1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TipoMembresiaLbl1.setForeground(new java.awt.Color(153, 153, 153));
        TipoMembresiaLbl1.setText("Tipo de Membresia:");

        CedulaTxt.setBackground(new java.awt.Color(204, 204, 204));
        CedulaTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        CedulaTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CedulaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaTxtActionPerformed(evt);
            }
        });

        CedulaLbl1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CedulaLbl1.setForeground(new java.awt.Color(153, 153, 153));
        CedulaLbl1.setText("Nombre Usuario:");

        NombreTxt1.setBackground(new java.awt.Color(204, 204, 204));
        NombreTxt1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoMembresiaLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CedulaLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CedulaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CedulaTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CedulaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(CedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CedulaLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CedulaTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NombreTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipoMembresiaLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CedulaTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaTxt1ActionPerformed

    private void AddLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLblMouseClicked
        DisableorActiveAll(true);
     jComboBox1.addItem("Administrador");
     jComboBox1.addItem("Entrenador");

    }//GEN-LAST:event_AddLblMouseClicked

    private void buscarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarLblMouseClicked
        jComboBox1.removeAllItems();
        ClearTxt();
        DisableorActiveAll(false);
        this.CedulaLbl.setText("Id del usuario a buscar:");
        this.CedulaLbl.setEnabled(true);
        this.CedulaLbl.setVisible(true);
        this.CedulaTxt.setEnabled(true);
        this.CedulaTxt.setText("");
        this.CedulaTxt.setVisible(true);

    }//GEN-LAST:event_buscarLblMouseClicked

    private void DeleteLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteLblMouseClicked
jComboBox1.removeAllItems();
        ClearTxt();
        DisableorActiveAll(false);
        this.CedulaLbl.setText("Id del usuario a eliminar");
        this.CedulaLbl.setEnabled(true);
        this.CedulaLbl.setVisible(true);
        this.CedulaTxt.setEnabled(true);
         this.CedulaTxt.setText("");
        this.CedulaTxt.setVisible(true);
    }//GEN-LAST:event_DeleteLblMouseClicked

    private void ActualizarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarLblMouseClicked
        jComboBox1.removeAllItems();
        ClearTxt();
        DisableorActiveAll(false);
          jComboBox1.addItem("Administrador");
          jComboBox1.addItem("Entrenador");
        this.CedulaLbl.setEnabled(true);
        this.CedulaLbl.setVisible(true);
        this.CedulaTxt.setEnabled(true);
     this.TipoMembresiaLbl1.setEnabled(true);
        this.TipoMembresiaLbl1.setVisible(true);
        this.jComboBox1.setEnabled(true);
        this.jComboBox1.setVisible(true);
       
    }//GEN-LAST:event_ActualizarLblMouseClicked

    private void ListoLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListoLblActionPerformed

        if (!this.CedulaTxt1.getText().isEmpty()
                && !this.CedulaTxt1.getText().isEmpty() ) {

            try {
                       
                Usuario emp = new Usuario(
                        this.CedulaTxt1.getText(),
                        this.CedulaTxt1.getText(),
                        this.jComboBox1.getSelectedItem().toString());
                    dao.create(mapper.toDTO(emp));
                     ClearTxt();
                  DisableorActiveAll(false);
            } catch (SQLException ex) {
                Logger.getLogger(GUIUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        } else if (this.CedulaLbl.getText().equals("Id del usuario a buscar:")) {

            Usuario emp;
            try {
                if (dao.validatePk(Integer.parseInt(this.CedulaTxt.getText()))){
                emp = mapper.toEnt(dao.read(Integer.valueOf(this.CedulaTxt.getText())));
                CedulaTxt.setText(String.valueOf(emp.getId()));
                CedulaTxt1.setText(emp.getUsername());
                NombreTxt1.setText(emp.getPasswordHash());
                jComboBox1.addItem(emp.getRol());
                
                }else {
                    JOptionPane.showMessageDialog(null, "El usuario no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(GUIUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            DisableorActiveAll(true);

        } else if (this.CedulaLbl.getText().equals("Id del usuario a eliminar")) {
            try {
                if (dao.validatePk(Integer.parseInt(this.CedulaTxt.getText()))) {
                    dao.delete(Integer.valueOf(CedulaTxt.getText()));
                    ClearTxt();
                    
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
                  
                }
            } catch (SQLException ex) {
                Logger.getLogger(GUIUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                if (dao.validatePk(Integer.parseInt(this.CedulaTxt.getText()))) {
                    Cliente cliente = new Cliente (Integer.parseInt(CedulaTxt.getText()),CorreoTxt.getText(),TelTxt.getText(),jComboBox1.getSelectedItem().toString());
                    dao.update(mapper.toDTO(cliente));
                      DisableorActiveAll(false);
                    
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario no existe", "informacion incorrecta", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(GUIUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ListoLblActionPerformed

    private void CancelLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelLblActionPerformed
        // TODO add your handling code here:
        DisableorActiveAll(false);
        ClearTxt();
    }//GEN-LAST:event_CancelLblActionPerformed

    private void CedulaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaTxtActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void NombreTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxt1ActionPerformed

    public String obtenerDetallesPaquetes(String id) {
        /*StringBuilder detalles = new StringBuilder();
       ArrayList<Paquete> valuesList = convertirHashMapAArrayList(listE.SearchCliente(id).getPaquetes().getPaquetesL());
    for (Paquete paquete : valuesList) {
        detalles.append(paquete.toString()).append("\n");
    }
    return detalles.toString();
}
  public static ArrayList<Paquete> convertirHashMapAArrayList(HashMap<String, Paquete> map) {
        ArrayList<Paquete> listaPaquetes = new ArrayList<>();
        // Recorrer el HashMap y agregar los valores al ArrayList
        for (Map.Entry<String, Paquete> entry : map.entrySet()) {
            listaPaquetes.add(entry.getValue());
        }

        return listaPaquetes;*/
        return null;
        /*StringBuilder detalles = new StringBuilder();
       ArrayList<Paquete> valuesList = convertirHashMapAArrayList(listE.SearchCliente(id).getPaquetes().getPaquetesL());
    for (Paquete paquete : valuesList) {
        detalles.append(paquete.toString()).append("\n");
    }
    return detalles.toString();
}
  public static ArrayList<Paquete> convertirHashMapAArrayList(HashMap<String, Paquete> map) {
        ArrayList<Paquete> listaPaquetes = new ArrayList<>();
        // Recorrer el HashMap y agregar los valores al ArrayList
        for (Map.Entry<String, Paquete> entry : map.entrySet()) {
            listaPaquetes.add(entry.getValue());
        }

        return listaPaquetes;*/
    }

    public void DisableorActiveAll(boolean bool) {

        this.CedulaLbl.setText("Id del Usuario:");
        this.CedulaLbl.setEnabled(bool);
        this.CedulaLbl.setVisible(bool);
        this.CedulaTxt.setEnabled(bool);
        this.CedulaTxt.setVisible(bool);
        this.CedulaTxt1.setEnabled(bool);
        this.CedulaTxt1.setVisible(bool);
        this.NombreLbl.setEnabled(bool);
        this.NombreLbl.setVisible(bool);  
        this.TipoMembresiaLbl1.setEnabled(bool);
        this.TipoMembresiaLbl1.setVisible(bool);
        this.jComboBox1.setEnabled(bool);
        this.jComboBox1.setVisible(bool);
        this.CedulaTxt1.setEnabled(bool);
        this.CedulaTxt1.setVisible(bool);
        this.CedulaLbl1.setEnabled(bool);
        this.CedulaLbl1.setVisible(bool);      
    }

    public void ClearTxt() {
        this.CedulaTxt.setText("");
        this.CedulaTxt1.setText("");
        this.CedulaTxt1.setText("");
        
    }

    public void showError(String err) {
        JOptionPane.showMessageDialog(this, err, "Error", JOptionPane.ERROR_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualizarLbl;
    private javax.swing.JLabel AddLbl;
    private javax.swing.JButton CancelLbl;
    private javax.swing.JLabel CedulaLbl;
    private javax.swing.JLabel CedulaLbl1;
    private javax.swing.JFormattedTextField CedulaTxt;
    private javax.swing.JTextField CedulaTxt1;
    private javax.swing.JLabel DeleteLbl;
    private javax.swing.JButton ListoLbl;
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JTextField NombreTxt1;
    private javax.swing.JLabel TipoMembresiaLbl1;
    private javax.swing.JLabel buscarLbl;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
